name: Create .mcaddon from repository contents

on:
  push:
    branches:
      - main
    paths:
      - "src/**"

  workflow_dispatch:

jobs:
  build:
    name: Assemble add-on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout resource pack contents
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run build script
        uses: ./.github/actions/build/
      - name: Build mcpack archive
        run: |
          sudo apt-get update
          sudo apt-get -y install zip
          cd ${GITHUB_WORKSPACE}
          zip -r -0 JG-RTX.mcaddon ./dist/RP ./dist/BP

      - name: Upload mcpack
        uses: actions/upload-artifact@v2
        with:
          name: JG-RTX Add-on
          path: JG-RTX.mcaddon
